provider: ${LEM_PROVIDER:stub}  # stub|openai|ollama
openai:
  model: gpt-4o-mini
  base_url: https://api.openai.com/v1
ollama:
  model: llama3.1
verifier:
  mode: real  # real|stub
  maj_k: 5
  pass_at_k: 1
rzero:
  samples_per_step: 6
  log_dir: ./artifacts/rzero
ttddr:
  steps: 12
  topk: 4
metrics:
  ece_bins: 10
adapters:
  shadow_window: 200
  canary_traffic: 0.05
  promotion_thresholds:
    cost_per_1k: 0.02
guards:
  lyapunov_deriv_max: 0.0
  oci_minimum: 0.8
  ece_limit: 0.05
  latency_p95_ms: 1500
budgets:
  gpu_memory_gb: 24
  token_usage: 1000000
  hourly_cost: 5.0
