provider: ${LEM_PROVIDER:stub}  # stub|openai|ollama
openai:
  model: gpt-4o-mini
  base_url: https://api.openai.com/v1
ollama:
  model: llama3.1
verifier:
  mode: real  # real|stub
  maj_k: 5
  pass_at_k: 1
rzero:
  samples_per_step: 6
  log_dir: ./artifacts/rzero
ttddr:
  steps: 12
  topk: 4
metrics:
  ece_bins: 10
adapters:
  shadow_window: 200
  canary_traffic: 0.05
  promotion_thresholds:
    ece: 0.05
    latency_p95_ms: 1500
    cost_per_1k: 0.02
