site_name: Memori
site_description: The Open-Source Memory Layer for AI Agents & Multi-Agent Systems
site_author: Harshal More
site_url: https://GibsonAI.github.io/memori

repo_name: memori
repo_url: https://github.com/GibsonAI/memori
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Usage: getting-started/basic-usage.md
  - Features: features.md
  - Architecture: architecture.md
  - Configuration:
    - Settings: configuration/settings.md
    - Database Setup: configuration/database.md
  - Conscious Ingestion:
    - Overview: conscious-ingestion/overview.md
    - Agents: conscious-ingestion/agents.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/memori
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/memorisdk/

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js