trigger:
- master
- dev

jobs:
- job: 'Tests'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'
      Python313:
        python.version: '3.13'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip wheel
    displayName: 'Install build tools'

  - script: |
      pip install .
    displayName: 'Install library'

  - script: |
      pip install pytest pytest-azurepipelines pytest-cov
      pytest .
    displayName: 'Run tests'

# - job: 'Lint'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.9'

#   - script: |
#       pip install flake8
#       flake8 .
#     displayName: 'Run linting'
